Wait for proper IP when creating agent config
codilime/contrail-windows-ci pull request #11
Opened 2018-01-03 13:57 UTC by krdln

This should fix some of the flakiness in multihost tests.

2018-01-04 10:34 UTC, kaweue requested changes

2018-01-04 10:34 UTC, kaweue commented on CIScripts/Test/TestConfigurationUtils.ps1
> +        $WAIT_TIME_FOR_DHCP_IN_SECONDS = 60
Could it be done by calling something similar to dhclient on windows like maybe  'ipconfig /renew' ?

For example:
You could check if there is valid address from dhcp using https://blogs.msdn.microsoft.com/virtual_pc_guy/2015/07/31/powershell-direct-waiting-for-an-ip-address/

After that you could call ipconfig /release; ipconfig /renew on selected interface.

2018-01-04 10:46 UTC, jablonskim requested changes

2018-01-04 10:46 UTC, jablonskim commented on CIScripts/Test/TestConfigurationUtils.ps1
> +        $WAIT_TIME_FOR_DHCP_IN_SECONDS = 60
I think we should create new function (`Wait-InterfaceIP` maybe), move the code there (with all changes requested by @PawelMarchewkaCodiLime) and call it from `Initialize-TestConfiguration` to have valid IP address in every case.

2018-01-08 10:06 UTC, kaweue requested changes

2018-01-08 10:06 UTC, kaweue commented on CIScripts/Test/TestConfigurationUtils.ps1
> +        $HNSTransparentAdapter = Get-RemoteNetAdapterInformation -Session $Session -AdapterName $TestConfiguration.VHostName
We think that this should be rather in `Initialize-TestConfiguration`, since `Initialize-ComputeServices` is not used everywhere (`Test-InitialPkt0Injection`, `Send-UDPPacket`).

2018-01-08 10:06 UTC, PawelMarchewkaCodiLime commented on CIScripts/Test/TestConfigurationUtils.ps1
> +            $AdapterConfig.RenewDHCPLease() | Out-Null
We think we should check if it succeeded. Please look here (https://msdn.microsoft.com/en-us/library/aa393064(v=vs.85).aspx). Maybe throw an exception when return value is other than 0.

2018-01-08 13:08 UTC, krdln commented
Testing revealed that `.RenewDHCPLease()` doesn't work reliably. On my computer, renewing a valid IP succeeds, but on testbeds, it fails after after about 30 seconds. Perhaps it's because the interface is used by vrouter? Anyway, I think we should go with loop here.

2018-01-08 15:47 UTC, kaweue approved these changes

2018-01-09 10:09 UTC, m-kostrzewa commented
btw please add ticket number to PR title

2018-01-09 10:15 UTC, jablonskim approved these changes

2018-01-09 11:43 UTC, merged