[WIP] JW-1344: use zuul-cloner to checkout repositories
codilime/contrail-windows-ci pull request #16
Opened 2018-01-08 14:02 UTC by sodar

2018-01-09 10:13 UTC, m-kostrzewa commented on ansible/roles/builder/tasks/main.yml
> +    creates: C:\Python27\Scripts\zuul-cloner.exe
Maybe we should switch to using requirements.txt? http://docs.ansible.com/ansible/latest/pip_module.html

2018-01-09 10:14 UTC, m-kostrzewa commented on CIScripts/Build/Zuul.ps1
> +        $Env:GERRIT_URL
Maybe it would be better to pass `GERRIT_URL` via a param? So there are no hidden globals used all over the code

2018-01-09 12:13 UTC, krdln commented on ansible/roles/builder/tasks/main.yml
> +  win_command: pip install zuul==2.6.0
Perhaps we can use the [pip module](http://docs.ansible.com/ansible/latest/pip_module.html) here? (Not sure if it works on windows though)

2018-01-10 15:52 UTC, jacek-izykowski requested changes
What do you think about extracting environment variables in top-level script and passing them explicitly (e.g. GERRIT_URL)?

KR, JI

2018-01-11 16:26 UTC, jacek-izykowski approved these changes
KR, JI

2018-01-12 13:00 UTC, kaweue approved these changes

2018-01-12 15:14 UTC, merged