Gerrit integration
codilime/contrail-windows-ci pull request #2
Opened 2017-12-15 14:38 UTC by jacek-izykowski

2017-12-18 08:54 UTC, jacek-izykowski commented
Janie, przetestuj proszę

2017-12-19 09:43 UTC, m-kostrzewa commented
Janie, przetestuj proszę

2017-12-21 09:49 UTC, jacek-izykowski commented
Janie, przetestuj proszę

2017-12-21 10:15 UTC, jacek-izykowski commented
Janie, przetestuj proszę

2017-12-21 15:34 UTC, m-kostrzewa requested changes

2017-12-21 15:34 UTC, m-kostrzewa commented on CIScripts/Build/BuildFunctions.ps1
>              & "$Env:GOPATH\bin\dep.exe" ensure -v
don't we want to disable this as well?

2017-12-22 09:58 UTC, merged