[WIP] Refactor deploy-demo-env
codilime/contrail-windows-ci pull request #21
Opened 2018-01-10 15:50 UTC by sodar

2018-01-11 13:32 UTC, sodar commented
To reviewers: commit `3f38c5e9c04e1c680ce13451f0b87b3a46221c3f` only adds original files from internal repository

2018-01-12 12:17 UTC, kaweue requested changes

2018-01-12 12:17 UTC, kaweue commented on ansible/roles/vmware-vm/tasks/destroy.yml
> +    folder: "{{ datacenter_name }}/vm/{{ testenv_folder }}"
Is this required (folder) ?

2018-01-12 12:17 UTC, PawelMarchewkaCodiLime commented on jenkinsfiles/Jenkinsfile.destroy-demo-env
> +}
Missing line

2018-01-15 09:36 UTC, sodar commented on ansible/roles/vmware-vm/tasks/destroy.yml
> +    folder: "{{ datacenter_name }}/vm/{{ testenv_folder }}"
Yes, specifying a folder is required

2018-01-15 09:42 UTC, kaweue approved these changes

2018-01-15 12:33 UTC, merged