JW-1307: make create-builder-template work on Codilime's CI
codilime/contrail-windows-ci pull request #7
Opened 2017-12-19 16:15 UTC by sodar

- Moved original roles/vars from previous repository

    ```
    Author: Michał Bilski <michal.bilski@codilime.com>
    Author: Michał Kostrzewa <michal.kostrzewa@codilime.com>
    Author: Wojciech Urbański <wojciech.urbanski@codilime.com>
    ```

- Moved `create-builder-template` pipeline script to Jenkinsfile
- Fix some deployment issues

2017-12-20 12:05 UTC, jacek-izykowski submitted a review, later dismissed

2017-12-20 12:24 UTC, m-kostrzewa commented
@sodar which changes are file moves and which are actual changes to code?

2017-12-20 12:31 UTC, wurbanski requested changes
Please show us what changed :).

2017-12-20 12:31 UTC, wurbanski commented on jenkinsfiles/Jenkinsfile.create-builder-template
> +withCredentials([usernamePassword(credentialsId: 'e9f31c41-6d0e-4950-b6d7-1aa7080468aa', passwordVariable: 'VC_PASSWORD', usernameVariable: 'VC_USERNAME')]) {
Consider reworking this to follow *declarative pipeline* style from `Jenkinsfile.deploy-builder` in the old repository.
Please. Strongly consider.

2017-12-20 15:37 UTC, sodar commented
@wurbanski @m-kostrzewa Sorry about the mess with the commits. I have rebased the changes, so that all moved/copied code is in one commit, i.e. the earliest commit in this PR.

I need to test the rest of the changes and refactor Jenkinsfile for create-builder-template so I mark this PR as WIP.

2017-12-21 10:15 UTC, sodar commented
PR is ready for review. Commit with hash `999986...` contains my changes.

2017-12-21 13:24 UTC, wurbanski approved these changes
LGTM

2017-12-21 13:59 UTC, m-kostrzewa approved these changes

2017-12-21 20:12 UTC, merged