WIP: Deploy VM from template using vSphere API
codilime/contrail-windows-ci pull request #70
Opened 2018-02-06 15:39 UTC by sodar

2018-02-06 16:42 UTC, m-kostrzewa submitted a review, later dismissed
Good effort overall, gj.

Aside from the comments, I would also try to have more logging output. I would recommend using `import logging`.

Also, we need more unit tests and maybe even integration tests that would run this in CI. We do expect to change this code in the future, after all.

2018-02-06 16:42 UTC, m-kostrzewa commented on ansible/vmware_common.py
> +    datastores = [d for d in host.datastore if 'ssd' in d.name]
Is hardcoded string `'ssd'` dependent on actual infrastructure names? If so, we should probably make it a param or something.

2018-02-06 16:42 UTC, m-kostrzewa commented on ansible/vmware_common.py
> +        raise Exception("Couldn't find the Folder with the provided name "
In all cases in the code, `Exception` class is too generic. I would either choose a more specific subclass from here https://docs.python.org/3/library/exceptions.html (in this case, maybe `FileNotFoundException` would work), or create my own subclass, like `VMWareException` / `ResourceNotFoundException`...

2018-02-06 16:42 UTC, m-kostrzewa commented on ansible/deploy_vm_from_template.py
> +           isinstance(device, vim.vm.device.VirtualSriovEthernetCard):
All these classes extend `VirtualEthernetCard` (https://www.vmware.com/support/developer/converter-sdk/conv55_apireference/vim.vm.device.VirtualEthernetCard.html) - maybe we can only check 
`isinstance(device, vim.vm.device.VirtualEthernetCard)`?

2018-02-06 16:42 UTC, m-kostrzewa commented on ansible/deploy_vm_from_template.py
> +                            vm_administrator='Administrator'):
This smells of too many params

2018-02-06 16:42 UTC, m-kostrzewa commented on ansible/deploy_vm_from_template.py
> +
[Personal taste], but these newlines seem unnecessary, especially since we have big indents. Personnaly I would remove them. I can't find what pep8 says about this.

2018-02-06 16:42 UTC, m-kostrzewa commented on ansible/deploy_vm_from_template.py
> +                        help='vSphere service to connect to')
Help text `vSphere service to connect to` is confusing when the param is called `build-id`. Could you expand the help a little bit?

2018-02-06 16:42 UTC, m-kostrzewa commented on ansible/deploy_vm_from_template.py
> +def get_nic_with_updated_network(content, nic_device, network_name):
Looking at the context in which this function is used, maybe calling it `get_nic_update_network_operation` would be better?

2018-02-06 16:42 UTC, m-kostrzewa commented on ansible/deploy_vm_from_template.py
> +                            vm_administrator='Administrator'):
Hmm how would I pursue refactoring this...
* arguments with `vm` prefix look like some class.

2018-02-06 16:42 UTC, m-kostrzewa commented on ansible/deploy_vm_from_template.py
> +                            vm_administrator='Administrator'):
So looking through this function, I've drawn this diagram. It shows whether a variable (or parameter) is required to get another param. It forms a DAG. We can look for clusters to guide our refactoring.
![dario1](https://user-images.githubusercontent.com/9220158/35870412-e35fd748-0b61-11e8-8d9d-072d27dd08c3.jpg)

One such clustering could look like this:
![dario2](https://user-images.githubusercontent.com/9220158/35870844-fd1309e8-0b62-11e8-8dc3-62ffbce10ddb.jpg)

From this we can see classes with constructors / function signatures like:
`connection(service_instance, datacenter_name, cluster_name)`
`config_spec(connection, template)`
`relocation_spec(connection, build_id)`
`customization_spec(identity, data_ip_address, data_network)`
`identity(vm_name, vm_password, vm_org, vm_administrator)`
`data_guest_map(data_ip_address, data_netmask)`
`clone_spec(config_spec, relocation_spec, customizatoin_spec)`
`task(clone_spec, service_instance, destination_folder, vm_name)`

Note: of course there are dozens of ways to cluster that graph. It is just a helper.

2018-02-06 16:42 UTC, m-kostrzewa commented on ansible/vmware_common.py
> +def find_vm_folder(conn, folder_path):
Are we actually finding the folder or getting it? I know we call `FindByInventoryPath` below but it looks like `folder_path` is known? If so, maybe renaming this function to `get_vm_folder` would be better.

2018-02-06 16:42 UTC, m-kostrzewa commented on ansible/vmware_common.py
> +    return dest_host
[Personal taste] I don't like these empty lines.

2018-02-06 16:42 UTC, m-kostrzewa commented on ansible/vmware_common.py
> +        time.sleep(1)
I would be scared running this in prod with no timeout. I know that in theory Jenkins should just kill this job if it sleeps for too long, but we never know when someone disables/misconfigures timeouts on Jenkins or something. I think we should be defensive here.

2018-02-06 16:42 UTC, m-kostrzewa commented on ansible/deploy_vm_from_template.py
> +                            vm_administrator='Administrator'):
BTW similar refactoring method could be used in other parts of the code, like `get_nic_with_updated_network` function.

2018-02-07 09:17 UTC, kaweue requested changes

2018-02-07 09:17 UTC, kaweue commented on ansible/deploy_vm_from_template.py
> +    if not args.password:
I don't think we need that. Do we?  As I understand we are going to use this script in CI.

2018-02-07 09:17 UTC, kaweue commented on ansible/deploy_vm_from_template.py
> +def get_args():
There is so many required arguments, maybe this configuration could be loaded from some file, like JSON file or even YAML....

2018-02-07 09:17 UTC, kaweue commented on ansible/deploy_vm_from_template.py
> +def get_args():
Name of the file could be passed as an argument.

2018-02-07 09:17 UTC, kaweue commented on ansible/deploy_vm_from_template.py
> +            device_list.append(device)
Maybe just create and return list here

2018-02-07 09:17 UTC, kaweue commented on ansible/deploy_vm_from_template.py
> +def deploy_vm_from_template(service_instance, datacenter_name, cluster_name, template_name,
I have to agree this functions is a bit longish

2018-02-07 09:17 UTC, kaweue commented on ansible/deploy_vm_from_template.py
> +    eth0 = get_nic_with_updated_network(connection.content, current_network_devices[0], mgmt_network_name)
Is it really eth0 or just primary interface ?

2018-02-07 09:17 UTC, kaweue commented on ansible/deploy_vm_from_template.py
> +    Disconnect(service_instance)
Shouldn't we Disconnect anyway even in case of exception in some cases (like exception in deploy_vm_from_template)?

2018-02-07 09:17 UTC, kaweue commented on ansible/deploy_vm_from_template.py
> +        service_instance = SmartConnectNoSSL(host=args.host, user=args.user, pwd=args.password)
Could we use somthing like this ```with SmartConnection(host=args.host, user=args.user, pwd=args.password) as service ``` without using try and except ??

2018-02-07 09:17 UTC, kaweue commented on ansible/deploy_vm_from_template.py
> +    vm.wait_for_task(service_instance, task)
Why can't we use method WaitForTask from task ?

2018-02-07 09:17 UTC, kaweue commented on ansible/vmware_common.py
> +    while task.info.state in ['queued', 'running']:
Are those values documented somewhere ?

2018-02-07 09:17 UTC, kaweue commented on ansible/deploy_vm_from_template.py
> +    eth0 = get_nic_with_updated_network(connection.content, current_network_devices[0], mgmt_network_name)
Could we just make a loop for all specified interfaces ?

2018-02-07 09:17 UTC, kaweue commented on ansible/deploy_vm_from_template.py
> +    parser.add_argument('--mgmt-network',
Maybe this code could be a bit more generic if we were able to pass list of networks with some parameters. In current solution if we would like to set up fixed ip in mgmt-network for a particular VM, we have to change that python code not only configuration.

2018-02-07 10:17 UTC, sodar commented on ansible/deploy_vm_from_template.py
> +           isinstance(device, vim.vm.device.VirtualSriovEthernetCard):
👍

2018-02-07 10:18 UTC, sodar commented on ansible/deploy_vm_from_template.py
> +                        help='vSphere service to connect to')
This help text is incorrect. It was left after copy-pasting `add_argument`. I will provide the correct message there.

2018-02-12 14:43 UTC, sodar commented
recheck no bug

2018-02-13 11:31 UTC, kaweue requested changes

2018-02-13 11:31 UTC, kaweue commented on ansible/files/provision_vm.py
> +                        help='User name to use')
please remove obvious comments

2018-02-13 11:31 UTC, kaweue commented on ansible/files/provision_vm.py
> +    api.wait_for_task(task)
Please call WaitForTask on task

2018-02-13 13:30 UTC, mclapinski requested changes

2018-02-13 13:30 UTC, mclapinski commented on ansible/files/vmware_api.py
> +    def wait_for_task(self, task):
https://i.imgur.com/0oepTPd.jpg

2018-02-13 14:20 UTC, mclapinski approved these changes

2018-02-13 14:28 UTC, kaweue approved these changes

2018-02-13 14:35 UTC, merged